### PR TITLE
Adding force delete a branch

### PR DESCRIPTION
**Pull request by martiansideofthemoon**
@arslanbilal , is this alright?

### CODE REVIEW

**Comment by arslanbilal** [comment]
Addition you commit is include in the cheat sheet and syntax is incorrect.

**Comment by martiansideofthemoon** [comment]
@arslanbilal Yeah but there isn't a forced delete command. There is a simple delete using `-d` flag. Forced delete uses `-D`

**Comment by arslanbilal** [comment]
ohh okay. I missed it. Can you create pull-request again?

**Comment by martiansideofthemoon** [comment]
@arslanbilal Thanks :smile: Anything else that I could work on?

**Comment by arslanbilal** [comment]
You can translate git cheat sheet to Hindi language and then creating a PR will be perfect :) @martiansideofthemoon

**Pull request merged**
