### PR TITLE
Hindi Git Cheat Sheet

### PR DESCRIPTION
**Pull request by martiansideofthemoon**
I've added a few sections of the Hindi version. Do tell me if it's looking okay before I proceed @arslanbilal

### CODE REVIEW

**Comment by arslanbilal** [comment]
Actually I don't understand what it is writing but the hierarchy look nice. After you complete the cheat sheet, I should check with google translator :D @martiansideofthemoon

**Comment by martiansideofthemoon** [comment]
@arslanbilal , I've more or less completed the cheat sheet :smile: I think I'll add git flow in another PR after understanding it. I hope it is okay :D

**Comment by arslanbilal** [comment]
Please check  
* [शाखाएं और टैग](#शाखाएं-और-टैग)
* [मर्ज और रिबेस](मर्ज-और-रिबेस)
* [पूर्ववत](पूर्ववत)
these. Not direct to the related infos

**Comment by martiansideofthemoon** [comment]
the first one is branches and tags. Tags in hindi is a bit vague.

the second one i've used the devanagari versions of merge and rebase. They are not proper hindi words. This is because merge is somewhat standard

**Comment by arslanbilal** [comment]
Okay, I merged this and you can still update properly. Thanks again! :+1:

**Pull request merged**
